### ISSUE TITLE
分时图

### ISSUE THREAD

**Issue by zslgod** [liihuu/klineweb#2]
显示分时图的api是哪个，
md文档中的配置样式的api，错了
能不能把web的源码，发一下，
0.0

**Comment by liihuu** [comment]
@zslgod 配置代码发一下

**Comment by zslgod** [comment]
我的意思是文档中的这个方法 chart.setCofig(config)
是不是应该是 chart.setConfig(config)，
还有就是，调用哪个方法，才能切换成分时图，或者，demo的代码让参考一下，我现在，只是能把，数据渲染上去，切换指标，其他的，就只能看代码，一点一点的试《》.《》

**Comment by liihuu** [comment]
@zslgod setConfig({candle:{chartType: 'time_line'})   具体的config 配置可以看  CONFIG_DETAIL.md这个文件

**Comment by zslgod** [comment]
好的，谢谢
