### ISSUE TITLE
Fix Blur Canvas [Chart + Crossair]

### ISSUE THREAD

**Issue by oxa0** [liihuu/klineweb#291]
### Version

8.5.0

### Steps to Reproduce

import klinecharts from "./chart";
import { useEffect, useRef } from "react";
import data from "./data.json";

function App() {
  const chRef = useRef(null);

  useEffect(() => {
    const el = chRef.current;
    el.style.width = `${window.innerWidth}px`;
    el.style.height = `${window.innerHeight}px`;

    const chart = klinecharts.init(el, {});
    chart.applyNewData(data);
  
  }, []);

  return <div ref={chRef}></div>;
}

export default App;

### Current Behavior

![Screenshot from 2022-08-09 13-34-47](https://user-images.githubusercontent.com/103932170/183637672-ae0d5ea7-d4b0-43ad-823f-f391f628b506.png)

### Expected Behavior

![GBPJPY_2022-08-09_13-36-15](https://user-images.githubusercontent.com/103932170/183637810-0c9a79db-cd52-4010-9fce-375abf04420c.png)

### Environment

```markdown
- OS:Ubuntu
- Browser:Brave
- Framework:React@18
```

**Comment by voladelta** [comment]
this relates to #258. should be closed.

you should read before open any issue to prevent waste maintainers' time.
