### ISSUE TITLE
走势图, 要怎么配置 - -...关闭？。。。

### ISSUE THREAD

**Issue by isszz** [liihuu/klineweb#309]
全部显示出来, 禁止左右拖动的模式

**Comment by liihuu** [comment]
需要自己计算一下，结合这几个api实现，`setScrollEnabled`，`getDataSpace`，`setOffsetRightSpace`，

**Comment by isszz** [comment]
> setOffsetRightSpace

要怎么处理全部渲染出来- -...

**Comment by liihuu** [comment]
一天内的数据个数是固定的，计算出一条数据需要的宽度，然后根据数据的实时个数算出右边需要的间隙，用`setOffsetRightSpace` 设置。
