### ISSUE TITLE
How to load more previous datas remotly ?

### ISSUE THREAD

**Issue by bcashier** [liihuu/klineweb#4]
Hi,

WHen dragging older datas, how to know to detect if the actual datas are ended and then load more and populate the chart please ?

Is there a way you share unminified script:
https://github.com/liihuu/klineweb/blob/master/dist/klinecharts.production.js

Thank you

**Comment by liihuu** [comment]
@bcashier Not supported yet, you can load enough data at once.

**Comment by bcashier** [comment]
@liihuu Thank you for your answer.

When adding new datas using chart.addData, it update the whole chart or only the part added like d3.js do by updating the dom?

Waiting ur anwer, interested in your project.

Thanks again in advance.

**Comment by liihuu** [comment]
@bcashier The entire chart is a combination of multiple canvases, rendered according to the situation.

**Comment by liihuu** [comment]
@bcashier Version 4.0.0 support load more.

**Comment by bcashier** [comment]
I will check that, big thanks.

**Comment by jinusean** [comment]
Is there any way to load past data, or do we have to reconstruct the chart from scratch?

**Comment by liihuu** [comment]
```javascript
loadMore(() => {
   // do it...
})
```
