### ISSUE TITLE
[Feature] 加载k线数据后，x时间轴能在未来没有k线的部分，显示时间

### ISSUE THREAD

**Issue by walkerxin** [liihuu/klineweb#418]
### 需求描述

能支持x轴未来部分显示时间，可以不用全部，例如 30分钟数据，之后的一个月能展示时间或者十字光标在的位置，显示时间（如图2）

### 具体实现

![图1 已有效果](https://user-images.githubusercontent.com/44486634/233549293-8e395a30-5033-409e-bf26-5954f9b9a592.png)

![图2 预期效果](https://user-images.githubusercontent.com/44486634/233549257-5038ef64-e1ff-4556-8ccb-3b007bc819c6.png)

**Comment by QGB** [comment]
怎么实现的 @walkerxin

**Comment by LeeZChuan** [comment]
可以造模拟数据，让你add进入的data所有值都是null或者空，但是时间戳依然存在，这样就可以正常显示底部的时间了

**Comment by QGB** [comment]
> 可以造模拟数据，让你add进入的data所有值都是null或者空，但是时间戳依然存在，这样就可以正常显示底部的时间了

这样还是有限的时间，能无限显示未来时间吗

**Comment by LeeZChuan** [comment]
> > 可以造模拟数据，让你add进入的data所有值都是null或者空，但是时间戳依然存在，这样就可以正常显示底部的时间了
> 
> 这样还是有限的时间，能无限显示未来时间吗

这里就要使用到图表的滑动事件了，在图表滑动的过程中，动态往前或者往后添加刚刚提到的上述数据，就可以了

**Comment by LeeZChuan** [comment]
但是实际，从业务的角度来说，很多金融k线图其实底部x轴也是没有数据的，因为无限长的数据是没有意义的，因为本来就是没数据，看x轴的日期也没有多大意义
