### ISSUE TITLE
Show current price horizontal line

### ISSUE THREAD

**Issue by bcashier** [liihuu/klineweb#5]
Hi,

Do current price with the horizontal line supported please ?

If not, do you have a plan for it ?!

I really like your chart, easy to use and manipulate !

Thanks

**Comment by liihuu** [comment]
Is last price?  Chart is supported.

**Comment by liihuu** [comment]
@bcashier Is last price? Chart is supported.

**Comment by bcashier** [comment]
@liihuu Yes the last price.

The chart support only the line and do not show the last price highlighted.

**Comment by liihuu** [comment]
@bcashier You can set the size and color of the line, but I don't know if it is what you want.

**Comment by bcashier** [comment]
@liihuu The line is good, but there is not the PRICE it self at the end of the line :)

**Comment by liihuu** [comment]
I think it can be added as a feature to a future release.

**Comment by liihuu** [comment]
@bcashier I think it can be added as a feature to a future release.

**Comment by bcashier** [comment]
Nice project, thank you sir.
